
name: Create new private repo

on: [workflow_dispatch]
    
jobs:
  tfsec-analysis:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code from main
      uses: actions/checkout@v3
    
    - name: Create a new repo
      run: .github/scripts/createRepo.sh marcsanp ${{ secrets.MYPERSTOKEN }} test-demo-repo
      
      
